### ISSUE TITLE
[Windows] ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by kilacoda** [willmcgugan/textual#14]
Trying to run the `textual.app` example on Windows 10 with Python 3.9.5:

 ```py
➜ python -m textual.app
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\app.py", line 19, in <module>
    from .driver import Driver
  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\driver.py", line 8, in <module>
    import curses
  File "C:\Program Files\Python39\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by willmcgugan** [comment]
OSX and Linux only for now I'm afraid. Thee will be a Windows version at some point.

**Comment by kilacoda** [comment]
I see. Might be a good idea to put that in the README for now then.

**Comment by yihong0618** [comment]
> Trying to run the `textual.app` example on Windows 10 with Python 3.9.5:
> 
> ```python
> ➜ python -m textual.app
> Traceback (most recent call last):
>  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
>    return _run_code(code, main_globals, None,
>  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
>    exec(code, run_globals)
>  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\app.py", line 19, in <module>
>    from .driver import Driver
>  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\driver.py", line 8, in <module>
>    import curses
>  File "C:\Program Files\Python39\lib\curses\__init__.py", line 13, in <module>
>    from _curses import *
> ModuleNotFoundError: No module named '_curses'
> ```

You can try install this https://github.com/zephyrproject-rtos/windows-curses
But a little buggy

**Comment by kilacoda** [comment]
Thanks, but it still doesn't work: 
```py
➜ python -m textual.app
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\app.py", line 20, in <module>
    from ._linux_driver import LinuxDriver
  File "C:\CodeProjects\Python\Manim\manimvenv\lib\site-packages\textual\_linux_driver.py", line 10, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
```

Looks like Textual is hardcoded to use some Unix only modules atm: https://docs.python.org/3/library/termios.html

**Comment by willmcgugan** [comment]
It is, yes. But at some point I will implement a Windows driver.

I’ll keep this ticket open to track that.

**Comment by lllama** [comment]
I've just had a look at the code and I see that there are no longer any references to `curses`. Will curses be making a reappearance? (Crossing my fingers that it won't, or at least won't be a core dependency as it never seems to play well on Windows.)

**Comment by willmcgugan** [comment]
Nope, no more curses.

**Comment by lskbr** [comment]
I have some routines for Windows here:
https://github.com/lskbr/colorconsole/blob/master/colorconsole/win.py

**Comment by udupa-varun** [comment]
For anyone interested, the repo examples seem to work pretty well on WSL2 (I'm using Ubuntu 20.04). I haven't explored any further.

I am seeing the "unclosed event loop" error when I run `easing.py`, but that is already being tracked in #127 and is probably unrelated to WSL.

**Comment by mhils** [comment]
Please feel free to also take inspiration from @mitmproxy's urwid Windows port: https://github.com/urwid/urwid/pull/448. It's not super beautiful, but at least we've shipped it and got few complaints. 😅

I don't recall if that was specific to urwid, but one particular annoyance we ran into was that Python's default event loop on Windows (ProactorEventLoop) does not support `event_loop.add_reader`. Our workaround is now to make use of tornado's AddThreadSelectorEventLoop[^1], which could probably be vendored if you don't need the rest of tornado.

[^1]: See https://bugs.python.org/issue37373, 
https://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.AddThreadSelectorEventLoop, 
https://github.com/mitmproxy/mitmproxy/commit/31f089cb8dae49a8cdb5d77c03088b62fcd1f910

**Comment by EpicCodeWizard** [comment]
The linux libraries used are `termios` and `tty` (excluding `curses`, there's windows port of that which works well). I can help out making a windows port, using `msvcrt` and `ctypes` (module replacements for windows), but don't want to do it all alone. If anyone's interested to work on it, please reply.

**Comment by UltraStudioLTD** [comment]
> The linux libraries used are `termios` and `tty` (excluding `curses`, there's windows port of that which works well). I can help out making a windows port, using `msvcrt` and `ctypes` (module replacements for windows), but don't want to do it all alone. If anyone's interested to work on it, please reply.

Do you have any C/C++ knowledge? You will need it and also knowledge of Win APIs

**Comment by EpicCodeWizard** [comment]
> > The linux libraries used are `termios` and `tty` (excluding `curses`, there's windows port of that which works well). I can help out making a windows port, using `msvcrt` and `ctypes` (module replacements for windows), but don't want to do it all alone. If anyone's interested to work on it, please reply.
> 
> Do you have any C/C++ knowledge? You will need it and also knowledge of Win APIs

Yes, I have some knowledge of them. I will start work on a windows port soon, anyone here can reply to help me out.
@willmcgugan Have you started work on a windows port already?

**Comment by willmcgugan** [comment]
Thanks @mhils The Urwid code was very helpful in understanding reading input in Windows!

**Comment by EpicCodeWizard** [comment]
I have done a lot of research on python CUI/TUI libraries and realized that `pywin32`, `ctypes`, and `msvcrt` are windows modules that can help to receive input. I will keep researching into other solutions, but I would recommend making one function, such as:
```python
import platform
if platform.system() == "Windows":
	def readkey():
		# the code
else:
	def readkey():
		# code
```

**Comment by sajjadhossanshimanto** [comment]
The only dam on the way to becoming famous is this windows support

**Comment by tusharsadhwani** [comment]
Will announced on twitter that his windows solution is partially ready. Just a bit more patience :)

https://twitter.com/willmcgugan/status/1484176989145554953?t=W4A0a-Oiwb_QZY5JX_TnfQ&s=19

**Comment by thedemons** [comment]
> Will announced on twitter that his windows solution is partially ready. Just a bit more patience :)
> 
> https://twitter.com/willmcgugan/status/1484176989145554953?t=W4A0a-Oiwb_QZY5JX_TnfQ&s=19

This is awesome, i wanna try it as fast as possible

**Comment by EpicCodeWizard** [comment]
> > Will announced on twitter that his windows solution is partially ready. Just a bit more patience :)
> > https://twitter.com/willmcgugan/status/1484176989145554953?t=W4A0a-Oiwb_QZY5JX_TnfQ&s=19
> 
> This is awesome, i wanna try it as soon as possible

Same, I really want to try it out :)!

**Comment by thedemons** [comment]
> > > Will announced on twitter that his windows solution is partially ready. Just a bit more patience :)
> > > https://twitter.com/willmcgugan/status/1484176989145554953?t=W4A0a-Oiwb_QZY5JX_TnfQ&s=19
> > 
> > 
> > This is awesome, i wanna try it as soon as possible
> 
> Same, I really want to try it out :)!

In case you didn't know (just like me).
Will has already created the windows branch [here](https://github.com/Textualize/textual/tree/windows-driver)
It is awesome, but it didn't work in vscode terminal for me. Both windows terminal and command prompt work fine.

**Comment by EpicCodeWizard** [comment]
> In case you didn't know (just like me). Will has already created the windows branch [here](https://github.com/Textualize/textual/tree/windows-driver) It is awesome, but it didn't work in vscode terminal for me. Both windows terminal and command prompt work fine.

As a side note, in no way do I mean to say this package is bad — it is an awesome package, and these are just some test results I've found. I have tested on all terminals on windows, which I have. On all programs, a weird message is printed after every press:
![=2s](https://emptyscarcecookie.epiccodewizard.repl.co/textual1.jpg)
VS Code and Atom built-in terminals don't have much support (Atom is worse than VS Code). Windows terminal doesn't support symbols, so add a way to disable them:
![symbol glitches](https://emptyscarcecookie.epiccodewizard.repl.co/textual2.jpg)
Powershell and Cygwin terminals both work fine.

**Comment by thedemons** [comment]
> > In case you didn't know (just like me). Will has already created the windows branch [here](https://github.com/Textualize/textual/tree/windows-driver) It is awesome, but it didn't work in vscode terminal for me. Both windows terminal and command prompt work fine.
> 
> As a side note, in no way do I mean to say this package is bad — it is an awesome package, and these are just some test results I've found. I have tested on all terminals on windows, which I have. On all terminals, a weird message is printed after every press: ![=2s](https://camo.githubusercontent.com/33db69905b629a87e335c854a4abbcf11bfa3b55930cb0ef5097330a6499d277/68747470733a2f2f656d707479736361726365636f6f6b69652e65706963636f646577697a6172642e7265706c2e636f2f7465787475616c312e6a7067) VS Code and Atom built-in terminals don't have much support (Atom is worse than VS Code). Windows terminal doesn't support symbols, so add a way to disable them:
> Powershell and Cygwin terminals both work fine.

Windows terminal (cmd and power shell) works very well for me.
It's usable in Command Prompt but the icons and color are off. It's a disaster in vscode terminal tho, font, color, icons aren't working, neither click, hover nor scrolling works.

I hope there will be a stable version for windows soon.

![windows terminal](https://i.imgur.com/btwaeiN.png)
![vscode terminal](https://i.imgur.com/3nXzr54.png)
![command prompt](https://i.imgur.com/HjvoXcQ.png)

**Comment by EpicCodeWizard** [comment]
[https://github.com/EpicCodeWizard/textual/tree/master](https://github.com/EpicCodeWizard/textual/tree/master)
Better Windows Driver: Fixes the cursor problem on `Powershell` and printing problem on all consoles. Now works (without glitches) on `Powershell`, `Cygwin`, and `Windows Terminal`. `VSCode/Atom Terminals` only send key presses to python, not cursor positions, scrolling, etc.

**Comment by EpicCodeWizard** [comment]
Hey everyone! I've created an improved windows driver for `textual`. [Link to the PR](https://github.com/Textualize/textual/pull/241)!

**Comment by thedemons** [comment]
> Hey everyone! I've created an improved windows driver for `textual`. [Link to the PR](https://github.com/Textualize/textual/pull/241)!

Great work! I'll definitely check it out

**Comment by EpicCodeWizard** [comment]
I have created a git repo with all the code for easier access. Just clone [https://github.com/EpicCodeWizard/textual-windows](https://github.com/EpicCodeWizard/textual-windows), then copy the `src/textual` folder in to your python `site-packages` folder.

**Comment by tusharsadhwani** [comment]
@ncwhale yeah, windows driver implementation has already been done. This issue should probably be closed as of now, unless there's more improvements to be made.
