### ISSUE TITLE
just learning....simple.py  gives errors 

### ISSUE THREAD

**Issue by vo1pwf** [willmcgugan/textual#23]
ran this to install
pip install Textual

$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    from textual import events
  File "/home/~~~~~/.local/lib/python3.8/site-packages/textual/events.py", line 7, in <module>
    from .message import Message
  File "/home/~~~~~/.local/lib/python3.8/site-packages/textual/message.py", line 7, in <module>
    from ._types import MessageTarget
  File "/home/~~~~~/.local/lib/python3.8/site-packages/textual/_types.py", line 31, in <module>
    Lines = list[list[Segment]]
TypeError: 'type' object is not subscriptable

am I wrong right from the get go?

**Comment by willmcgugan** [comment]
That's Python3.9 syntax. There's a fix in main if you want to install from the repo. Check it out and run the following:

```python
pip install poetry
poetry install
```

**Comment by willmcgugan** [comment]
Let me know if you run in to any more problems.
