### ISSUE TITLE
AttributeError: module 'textual.events' has no attribute 'Startup'

### ISSUE THREAD

**Issue by UltraStudioLTD** [willmcgugan/textual#47]
I get this error when testing examples

```
~/textual/examples $ python simple.py                   Traceback (most recent call last):                        File "/data/data/com.termux/files/home/textual/examples/simple.py", line 9, in <module>                           class MyApp(App):                                     File "/data/data/com.termux/files/home/textual/examples/simple.py", line 16, in MyApp                             async def on_startup(self, event: events.Startup) -> None:             
AttributeError: module 'textual.events' has no attribute 'Startup'                                     
```

**Comment by willmcgugan** [comment]
Think you have old code there. Try getting the latest.

**Comment by UltraStudioLTD** [comment]
I reinstalled and recloned repository and it worked.
Thanks
